name: Versioning Workflow

on:
  pull_request:
    types:
      - closed

jobs:
  update-versions:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Extract Module Updates from PR Description
      id: extract_updates
      run: |
        #!/bin/bash

        # Extract the pull request body
        PR_BODY=$(jq -r .pull_request.body < "$GITHUB_EVENT_PATH")

        # Initialize variables
        PATCH_MODULES=()
        MINOR_MODULES=()
        MAJOR_MODULES=()

        # Check for module updates
        while read -r line; do
          case $line in
            *"tree"* )
              MODULE_NAME="tree"
              ;;
            *"database"* )
              MODULE_NAME="database"
              ;;
            *"visualizer"* )
              MODULE_NAME="visualizer"
              ;;
            *"general_libraries"* )
              MODULE_NAME="general_libraries"
              ;;
            *"- [x] Patch update(s)"* )
              PATCH_MODULES+=($MODULE_NAME)
              ;;
            *"- [x] Minor update(s)"* )
              MINOR_MODULES+=($MODULE_NAME)
              ;;
            *"- [x] Major update(s)"* )
              MAJOR_MODULES+=($MODULE_NAME)
              ;;
          esac
        done <<< "$PR_BODY"

        # Save the modules to GitHub environment
        echo "PATCH_MODULES=${PATCH_MODULES[@]}" >> $GITHUB_ENV
        echo "MINOR_MODULES=${MINOR_MODULES[@]}" >> $GITHUB_ENV
        echo "MAJOR_MODULES=${MAJOR_MODULES[@]}" >> $GITHUB_ENV

    - name: Print Extracted Modules
      run: |
        echo "Patch Modules: ${{ env.PATCH_MODULES }}"
        echo "Minor Modules: ${{ env.MINOR_MODULES }}"
        echo "Major Modules: ${{ env.MAJOR_MODULES }}"

    - name: Update Patch Modules
      if: env.PATCH_MODULES != ''
      run: |
        for module in $PATCH_MODULES; do
          mvn -f $module/pom.xml build-helper:parse-version versions:set -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.nextIncrementalVersion}'
        done

    - name: Update Minor Modules
      if: env.MINOR_MODULES != ''
      run: |
        for module in $MINOR_MODULES; do
          mvn -f $module/pom.xml build-helper:parse-version versions:set -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.nextMinorVersion}.0'
        done

    - name: Update Major Modules
      if: env.MAJOR_MODULES != ''
      run: |
        for module in $MAJOR_MODULES; do
          mvn -f $module/pom.xml build-helper:parse-version versions:set -DnewVersion='${parsedVersion.nextMajorVersion}.0.0


    - name: Update Parent Properties
      run: |
        mvn versions:update-properties

    - name: Determine Overall Update Level
      id: update_level
      run: |
        if [ -n "$MAJOR_MODULES" ]; then
          echo "update_level=major" >> $GITHUB_ENV
        elif [ -n "$MINOR_MODULES" ]; then
          echo "update_level=minor" >> $GITHUB_ENV
        else
          echo "update_level=patch" >> $GITHUB_ENV
        fi

    - name: Run Python Script to Update Parent Version
      run: |
        python3 update_parent_version.py ${{ env.update_level }}

    - name: Update Child Modules
      run: |
        mvn -N versions:update-child-modules

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update module versions based on PR #${{ github.event.pull_request.number }}"
        git push origin main
